mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<int:user_id>', views.profile, name='profile'),

    path('password/find', views.password_find, name='password_find'),
    path('password/modify/<int:user_id>', views.password_modify, name='password_modify'),

    path('id/find/', views.id_find, name='id_find'),
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

mysite/pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('question/detail/<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    path('question/vote/del/<int:question_id>/', question_views.question_vote_del, name='question_vote_del'),
    path('question/list/<int:category_id>/', question_views.question_list, name='question_list'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
    path('answer/vote/del/<int:answer_id>/', answer_views.answer_vote_del, name='answer_vote_del'),

    # comment_views.py
    path('question/comment/create/<int:question_id>/', comment_views.question_comment_create, name='question_comment_create'),
    path('answer/comment/create/<int:answer_id>/<str:page_num>', comment_views.answer_comment_create, name='answer_comment_create'),
    path('comment/vote/<int:question_id>?<int:comment_id>', comment_views.comment_vote, name='comment_vote'),
    path('comment/vote/del/<int:question_id>?<int:comment_id>', comment_views.comment_vote_del, name='comment_vote_del'),
    path('comment/del/<int:question_id>?<int:comment_id>', comment_views.comment_delete, name='comment_delete'),
    path('comment/modify/<int:question_id>?<int:comment_id>', comment_views.comment_modify, name='comment_modify'),
]

mysite/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Count
from datetime import datetime, timedelta

from ..models import Question


def index(request):
    return redirect('pybo:question_list', category_id=1)


def detail(request, question_id):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    sort = request.GET.get('sort', 'recommend')

    question = get_object_or_404(Question, pk=question_id)
    if sort == 'recent':
        answer_list = question.answer_set.order_by('-modify_date')
    else:
        answer_list = question.answer_set.annotate(voter_count=Count('voter')).order_by('-voter_count')
    paginator = Paginator(answer_list, 5)
    page_obj = paginator.get_page(page)

    context = {'question': question, 'answer_list': page_obj, 'page': page, 'kw': kw, 'sort': sort}
    response = render(request, 'pybo/question_detail.html', context)

    # hit functions(cookie)
    expire_date, now = datetime.now(), datetime.now()
    expire_date += timedelta(days=1)
    expire_date = expire_date.replace(hour=0, minute=0, second=0, microsecond=0)
    expire_date -= now
    max_age = expire_date.total_seconds()
    cookie_value = request.COOKIES.get('hitQuestion', '_')

    if f'_{question_id}_' not in cookie_value:
        cookie_value += f'{question_id}_'
        response.set_cookie('hitQuestion', value=cookie_value, max_age=max_age, httponly=True)
        question.hits += 1
        question.save()

    return response

mysite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ko">
<head>
    <!-- Required meta tag -->
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <!-- Bootstrap CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'bootstrap.min.css' %}">
    <!-- pybo CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'style.css' %}">
    <!-- SimpleSDM CSS -->
    <link rel="stylesheet" type="text/css" href="{% static 'cdn.jsdelivr.net_npm_simplemde@1.11.2_dist_simplemde.min.css' %}">
    <title>Hello, pybo!</title>
</head>
<body>
    <!-- 네비게이션바 -->
    {% include "navbar.html" %}
    <!-- 기본 템플릿 안에 삽입될 내용 Start -->
    {% block content %}
    {% endblock %}
    <!-- 기본 템플릿 안에 삽입될 내용 End -->
    <!-- Bootstrap JS -->
    <script src="{% static 'bootstrap.min.js' %}"></script>
    <!-- fontawesome -->
    <script src="https://kit.fontawesome.com/c7dc2c74ff.js" crossorigin="anonymous"></script>
    <!-- SimpleSDM JS -->
    <script src="{% static 'cdn.jsdelivr.net_npm_simplemde@1.11.2_dist_simplemde.min.js' %}"></script>
    <!-- 자바 스크립트 Start -->
    {% block script %}
    {% endblock %}
    <!-- 자바 스크립트 End -->
</body>
</html>

mysite/templates/form_errors.html
<!-- 필드 오류와 넌필드 오류 출력-->
{% if form.errors %}
    <div class="alert alert-danger" style="align-content:center;">
        {% for field in form %}
            <!--필드 오류-->
            {% if field.errors %}
                <div>
                    <strong>{{ field.label }}</strong>
                    {{ field.errors }}
                </div>
            {% endif %}
        {% endfor %}
        <!--넌필드 오류-->
        {% for error in form.non_field_errors %}
            <div>
                <strong>{{ error }}</strong>
            </div>
        {% endfor %}
    </div>
{% endif %}

mysite/templates/messages_errors.html
{% if messages %}
    <div class="alert alert-danger my-3" role="alert">
    {% for message in messages %}
        <strong>{{ message.tags }}</strong>
        <ul><li>{{ message.message }}</li></ul>
    {% endfor %}
    </div>
{% endif %}

mysite/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-dark">
    <div class="container">
        <a class="navbar-brand" href="{% url 'pybo:index' %}">Pybo</a>
        <button class="btn btn-black d-inline-block d-lg-none m1-auto" type="button"
                data-bs-toggle="collapse"
                data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent"
                aria-expanded="false"
                aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent" data-bs-theme="dark">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link text-light" href="{% url 'common:logout' %}">{{ user.username }} (로그아웃)</a>
                    {% else %}
                        <a class="nav-link text-light" href="{% url 'common:login' %}">로그인</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    {% if not user.is_authenticated %}
                        <a class="nav-link text-light" href="{% url 'common:signup' %}">회원가입</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    {% if user.is_authenticated %}
                        <a class="nav-link text-light" href="{% url 'common:profile' user.id %}">프로필</a>
                    {% endif %}
                </li>
                <li class="nav-item">
                    <a class="nav-link text-light" href="{% url 'pybo:index' %}">게시판</a>
                </li>
            </ul>
        </div>
    </div>
</nav>

mysite/templates/sidebar.html
<nav id="sidebar">
    <div class="list-group">
        <a class="rounded-0 list-group-item list-group-item-action list-group-item-light"
           href="{% url 'pybo:question_list' 1 %}">질문&답변</a>
        <a class="rounded-0 list-group-item list-group-item-action list-group-item-light"
           href="{% url 'pybo:question_list' 2 %}">강좌</a>
        <a class="rounded-0 list-group-item list-group-item-action list-group-item-light"
           href="{% url 'pybo:question_list' 3 %}">자유게시판</a>
    </div>
</nav>