mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

mysite/pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('question/detail/<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    path('question/vote/del/<int:question_id>/', question_views.question_vote_del, name='question_vote_del'),
    path('question/list/<int:category_id>/', question_views.question_list, name='question_list'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
    path('answer/vote/del/<int:answer_id>/', answer_views.answer_vote_del, name='answer_vote_del'),

    # comment_views.py
    path('question/comment/create/<int:question_id>/', comment_views.question_comment_create, name='question_comment_create'),
    path('answer/comment/create/<int:answer_id>/<str:page_num>', comment_views.answer_comment_create, name='answer_comment_create'),
    path('comment/vote/<int:question_id>?<int:comment_id>', comment_views.comment_vote, name='comment_vote'),
    path('comment/vote/del/<int:question_id>?<int:comment_id>', comment_views.comment_vote_del, name='comment_vote_del'),
    path('comment/del/<int:question_id>?<int:comment_id>', comment_views.comment_delete, name='comment_delete'),
    path('comment/modify/<int:question_id>?<int:comment_id>', comment_views.comment_modify, name='comment_modify'),
]

mysite/pybo/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    subject = models.CharField(max_length=200)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_comment')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_comment')
    parent_content = models.TextField(null=True, default='')
    content = models.TextField(null=True, default='')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_comment')


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_question')
    subject = models.CharField(max_length=200)          # 글자 수의 길이가 제한된 텍스트를 이용할 때
    content = models.TextField(null=True, default='')   # 글자 수를 제한할 수 없는 텍스트를 이용할 때
    create_date = models.DateTimeField()                # 생성된 날짜와 시간에 관계된 필드.
    modify_date = models.DateTimeField(null=True, blank=True)               # 수정 날짜
    voter = models.ManyToManyField(User, related_name='voter_question')     # 추천인 추가
    comments = models.ManyToManyField(Comment, related_name='comment_question')
    hits = models.DecimalField(max_digits=7, decimal_places=0, default=0)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField(null=True, default='')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')
    comments = models.ManyToManyField(Comment, related_name='comment_answer')

mysite/pybo/forms.py
from django import forms
from pybo.models import Question, Answer, Comment


class QuestionForm(forms.ModelForm):
    class Meta:
        model = Question
        fields = ['category', 'subject', 'content']     # QustionFrom에서 사용할 Question 모델의 속성
        # for {{ form.as_p }}
        # widgets = {
        #     'subject': forms.TextInput(attrs={'class': 'form-control'}),
        #     'content': forms.Textarea(attrs={'class': 'form-control', 'rows': 10})
        # }
        labels = {
            'category': '게시판',
            'subject': '제목',
            'content': '내용',
        }


class AnswerForm(forms.ModelForm):
    class Meta:
        model = Answer
        fields = ['content']
        labels = {
            'content': '답변내용',
        }


class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['content']
        labels = {
            'content': '댓글내용'
        }

mysite/pybo/views/answer_views.py
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect, resolve_url
from django.utils import timezone
from django.db.models import Count

from ..forms import AnswerForm
from ..models import Question, Answer


@login_required(login_url='common:login')
def answer_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = AnswerForm(request.POST)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.author = request.user
            answer.create_date = timezone.now()
            answer.modify_date = answer.create_date
            answer.question = question
            answer.save()
            return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=question.id), answer.id))
    else:
        form = AnswerForm()
    page = request.GET.get('page', '1')
    answer_list = question.answer_set.annotate(voter_count=Count('voter')).order_by('-voter_count')
    paginator = Paginator(answer_list, 5)
    page_obj = paginator.get_page(page)
    context = {'question': question, 'answer_list': page_obj, 'page': page, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_modify(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '수정권한이 없습니다')
        return redirect('pybo:detail', question_id=answer.question.id)
    if request.method == "POST":
        form = AnswerForm(request.POST, instance=answer)
        if form.is_valid():
            answer = form.save(commit=False)
            answer.modify_date = timezone.now()  # 수정일시 저장
            answer.save()
            return redirect(
                '{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))
    else:
        form = AnswerForm(instance=answer)
    context = {'answer': answer, 'form': form}
    return render(request, 'pybo/answer_form.html', context)


@login_required(login_url='common:login')
def answer_delete(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.user != answer.author:
        messages.error(request, '삭제권한이 없습니다')
    else:
        answer.delete()
    return redirect('pybo:detail', question_id=answer.question.id)


@login_required(login_url='common:login')
def answer_vote(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    try:
        if request.user == answer.author:
            messages.error(request, '본인이 작성한 답변은 추천할 수 없습니다')
        elif request.user.voter_answer.all().get(id=answer_id):
            messages.error(request, '이미 추천을 누른답변은 추천할 수 없습니다')
    except Answer.DoesNotExist:
        answer.voter.add(request.user)
    return redirect('{}#answer_{}'.format(resolve_url('pybo:detail', question_id=answer.question.id), answer.id))


@login_required(login_url='common:login')
def answer_vote_del(request, answer_id):
    answer = get_object_or_404(Answer, pk=answer_id)
    answer.voter.remove(request.user)
    return redirect('pybo:detail', question_id=answer.question.id)

mysite/pybo/views/base_views.py
from django.core.paginator import Paginator
from django.shortcuts import render, get_object_or_404, redirect
from django.db.models import Count
from datetime import datetime, timedelta

from ..models import Question


def index(request):
    return redirect('pybo:question_list', category_id=1)


def detail(request, question_id):
    page = request.GET.get('page', '1')
    kw = request.GET.get('kw', '')
    sort = request.GET.get('sort', 'recommend')

    question = get_object_or_404(Question, pk=question_id)
    if sort == 'recent':
        answer_list = question.answer_set.order_by('-modify_date')
    else:
        answer_list = question.answer_set.annotate(voter_count=Count('voter')).order_by('-voter_count')
    paginator = Paginator(answer_list, 5)
    page_obj = paginator.get_page(page)

    context = {'question': question, 'answer_list': page_obj, 'page': page, 'kw': kw, 'sort': sort}
    response = render(request, 'pybo/question_detail.html', context)

    # hit functions(cookie)
    expire_date, now = datetime.now(), datetime.now()
    expire_date += timedelta(days=1)
    expire_date = expire_date.replace(hour=0, minute=0, second=0, microsecond=0)
    expire_date -= now
    max_age = expire_date.total_seconds()
    cookie_value = request.COOKIES.get('hitQuestion', '_')

    if f'_{question_id}_' not in cookie_value:
        cookie_value += f'{question_id}_'
        response.set_cookie('hitQuestion', value=cookie_value, max_age=max_age, httponly=True)
        question.hits += 1
        question.save()

    return response

mysite/pybo/views/comment_views.py
from django.core.paginator import Paginator
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, get_object_or_404, redirect
from django.utils import timezone
from django.db.models import Count

from ..forms import CommentForm
from ..models import Question, Answer, Comment


@login_required(login_url='common:login')
def question_comment_create(request, question_id):
    question = get_object_or_404(Question, pk=question_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.category = question.category
            comment.parent_content = question.subject
            comment.save()
            question.comments.add(comment)
            return redirect('pybo:detail', question_id=question_id)
    else:
        form = CommentForm()

    page = request.GET.get('page', '1')
    answer_list = question.answer_set.annotate(voter_count=Count('voter')).order_by('-voter_count')
    paginator = Paginator(answer_list, 5)
    page_obj = paginator.get_page(page)
    context = {'question': question, 'answer_list': page_obj, 'page': page, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def answer_comment_create(request, answer_id, page_num):
    answer = get_object_or_404(Answer, pk=answer_id)
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.author = request.user
            comment.create_date = timezone.now()
            comment.category = answer.question.category
            comment.parent_content = answer.content
            comment.save()
            answer.comments.add(comment)
            return redirect('pybo:detail', question_id=answer.question.id)
    else:
        form = CommentForm()

    question = get_object_or_404(Question, pk=answer.question_id)
    answer_list = question.answer_set.annotate(voter_count=Count('voter')).order_by('-voter_count')
    page = request.GET.get('page', page_num)
    paginator = Paginator(answer_list, 5)
    page_obj = paginator.get_page(page)
    context = {'question': question, 'answer_list': page_obj, 'page': page, 'form': form}
    return render(request, 'pybo/question_detail.html', context)


@login_required(login_url='common:login')
def comment_vote(request, question_id, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    try:
        if request.user == comment.author:
            messages.error(request, '본인이 작성한 댓글은 추천할 수 없습니다')
        elif request.user.voter_question.all().get(id=comment_id):
            messages.error(request, '이미 추천을 누른 댓글은 추천할 수 없습니다')
    except Question.DoesNotExist:
        comment.voter.add(request.user)
    return redirect('pybo:detail', question_id=question_id)


@login_required(login_url='common:login')
def comment_vote_del(request, question_id, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    comment.voter.remove(request.user)
    return redirect('pybo:detail', question_id=question_id)


@login_required(login_url='common:login')
def comment_delete(request, question_id, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '삭제권한이 없습니다.')
        return redirect('pybo:detail', question_id=question_id)
    comment.delete()
    return redirect('pybo:detail', question_id=question_id)


@login_required(login_url='common:login')
def comment_modify(request, question_id, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    if request.user != comment.author:
        messages.error(request, '수정권한이 없습니다.')
        return redirect('pybo:detail', question_id=question_id)
    if request.method == 'POST':
        form = CommentForm(request.POST, instance=comment)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.modify_date = timezone.now()
            comment.save()
            return redirect('pybo:detail', question_id=question_id)
    else:
        form = CommentForm(instance=comment)
    context = {'form': form}
    return render(request, 'pybo/comment_form.html', context)

mysite/templates/pybo/answer_comment.html
{% load pybo_filter %}
<div class="comment py-2 text-muted">
    {% if comment.voter.count %}
        <span class="text-danger">+{{ comment.voter.count }}</span>
    {% endif %}
    <span style="white-space: pre-line;" class="comment-content">{{ comment.content }}</span>
    - <span>
        <strong style="color:#01DFA5;">{{ comment.author }}</strong>님, {{ comment.modify_date }}
    </span>
    {% if request.user == comment.author %}
        <a href="{% url 'pybo:comment_modify' question.id comment.id  %}">수정,</a>
        <a href="javascript:void(0)" class="delete" data-uri="{% url 'pybo:comment_delete' question.id comment.id  %}">삭제,</a>
    {% endif %}
    {% if request.user|find_voter:comment %}
        <a href="javascript:void(0)" data-uri="{% url 'pybo:comment_vote_del' question.id comment.id  %}" class="unrecommend">
            추천 해제,</a>
    {% else %}
        <a href="javascript:void(0)" data-uri="{% url 'pybo:comment_vote' question.id comment.id %}" class="recommend">
            추천,</a>
    {% endif %}
    <a href="javascript:answer_comment_reply({{ answer.id }}, {{ comment.id }})" id="answer_comment{{ comment.id }}" data-author="{{ comment.author }}"> 대댓글</a>
</div>

mysite/templates/pybo/answer_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container my-3 py-3">
        <div class="row">
            <div id="content_box" class="py-2" style="height: auto !important;">
                <h5 class="my-3 border-bottom pb-2">답변등록</h5>
                <div class="mb-3">
                    <label for="content">질문내용</label>
                    <div class="p-2 bd-highlight fw-bold">{{ answer.question.content }}</div>
                </div>
                <form method="post">
                    {% csrf_token %}
                    {% include "form_errors.html" %}
                    <div class="mb-3">
                        <label for="content" class="form-label">답변내용</label>
                        <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
                    </div>
                    <button type="submit" class="btn btn-primary">저장하기</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript">
        const editor = new SimpleMDE();
    </script>
{% endblock %}

mysite/templates/pybo/comment_form.html
{% extends 'base.html' %}
{% block content %}
    <div class="container my-3 py-3">
        <div class="row">
            <div id="content_box" class="border-top border-secondary py-2" style="height: auto !important;">
                <h5 class="my-3 border-bottom pb-2">댓글 수정</h5>
                <form method="post">
                    {%  csrf_token %}
                    <!-- 오류 표시 Start -->
                    {% include 'form_errors.html' %}
                    <!-- 오류 표시 End -->
                    <div class="mb-3">
                        <label for="content" class="form-label">내용</label>
                        <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
                    </div>
                    <!-- {{ form.as_p }} -->
                    <button type="submit" class="btn btn-primary">저장하기</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

mysite/templates/pybo/question_comment.html
{% load pybo_filter %}
<div class="comment py-2 text-muted">
    {% if comment.voter.count %}
        <span class="text-danger">+{{ comment.voter.count }}</span>
    {% endif %}
    <span style="white-space: pre-line;" class="comment-content">{{ comment.content }}</span>
    - <span>
        <strong style="color:#01DFA5;">{{ comment.author }}</strong>님,
    {% if comment.modify_date %}
        수정: {{ comment.modify_date }}
    {% else %}
        {{ comment.create_date }}
    {% endif %}
    </span>
    {% if request.user == comment.author %}
    <a href="{% url 'pybo:comment_modify' question.id comment.id  %}">수정,</a>
    <a href="javascript:void(0)" class="delete" data-uri="{% url 'pybo:comment_delete' question.id comment.id  %}">삭제,</a>
    {% endif %}
    {% if request.user|find_voter:comment %}
        <a href="javascript:void(0)" data-uri="{% url 'pybo:comment_vote_del' question.id comment.id  %}" class="unrecommend">
            추천 해제,</a>
    {% else %}
        <a href="javascript:void(0)" data-uri="{% url 'pybo:comment_vote' question.id comment.id %}" class="recommend">
            추천,</a>
    {% endif %}
    <a href="javascript:question_comment_reply({{ comment.id }})" id="question_comment{{ comment.id }}" data-author="{{ comment.author }}">대댓글</a>
</div>

mysite/templates/pybo/question_form.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
    <div class="container my-3 py-3">
        <div class="row">
            <div id="content" class="border-top border-secondary py-2" style="height: auto !important;">
                <h5 class="my-3 border-bottom pb-2">질문등록</h5>
                <form method="post">
                    {%  csrf_token %}
                    <!-- 오류 표시 Start -->
                    {% include 'form_errors.html' %}
                    <!-- 오류 표시 End -->
                    <div class="mb-3">
                        <select class="form-select mb-3" aria-label="Default select example" id="category" name="category">
                            <option value="0">게시판</option>
                            <option value="1">질문&답변</option>
                            <option value="2">강좌</option>
                            <option value="3">자유게시판</option>
                        </select>
                        <input type="text" class="form-control mb-3" name="subject" id="subject" placeholder="제목"
                           value="{{ form.subject.value|default_if_none:'' }}">

                    </div>
                    <div class="mb-3">
                        <label for="content" class="form-label">내용</label>
                        <textarea class="form-control" name="content" id="content" rows="10">{{ form.content.value|default_if_none:'' }}</textarea>
                    </div>
                    <!-- {{ form.as_p }} -->
                    <button type="submit" class="btn btn-primary">저장하기</button>
                </form>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript">
        const editor = new SimpleMDE();
    </script>
{% endblock %}

mysite/templates/pybo/question_list.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
    <div class="container mt-3" style="height: auto !important;">
        <div class="row" style="height: auto !important;">
            <div class="col-sm-12 col-md-3 col-lg-2 p-2">
                {% include "sidebar.html" %}
            </div>
                <div class="col-sm-12 col-md-9 col-lg-10 p-2" style="height: auto !important;">
                    <div id="content_box" style="height: auto !important;">
                        <div class="container py-3">
                            <h5 class="border-bottom pb-2 mb-3">{{ category.subject }}</h5>
                            <!-- 검색 및 정렬 -->
                            <div class="row my-3">
                                <div class="col-6">
                                    <div class="btn-group" role="group" aria-label="Basic radio toggle button group">
                                        <input type="radio" class="btn-check" name="btnradio" id="btnradio1" value="recent" checked>
                                        <label class="btn btn-outline-secondary" for="btnradio1">
                                           <i class="fas fa-list"></i>
                                        </label>

                                        <input type="radio" class="btn-check" name="btnradio" id="btnradio2" value="recommend">
                                        <label class="btn btn-outline-secondary" for="btnradio2">
                                            <i class="fas fa-thumbs-up"></i>
                                        </label>

                                        <input type="radio" class="btn-check" name="btnradio" id="btnradio3" value="hot">
                                        <label class="btn btn-outline-secondary" for="btnradio3">
                                            <i class="fa-solid fa-fire"></i>
                                        </label>
                                    </div>
                                </div>
                                <div class="col-6">
                                    <div class="input-group">
                                        <input type="text" id="search_kw" class="form-control" value="{{ kw|default_if_none:'' }}">
                                        <div class="input-group-append">
                                            <button class="btn btn-outline-secondary" type="button" id="btn_search">찾기</button>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- 테이블 -->
                            <table class="table">
                                <thead>
                                <tr class="text-center table-dark">
                                    <th>추천</th>
                                    <th style="width:50%">제목</th>
                                    <th>글쓴이</th>
                                    <th>조회수</th>
                                    <th>작성일시</th>
                                </tr>
                                </thead>
                                <tbody>
                                {% if question_list %}
                                {% for question in question_list %}
                                    <tr class="text-center">
                                        <td class="align-middle">
                                            {% if question.voter.count > 0 %}
                                            <span class="badge badge-warning px-2 py-1">{{ question.voter.count }}</span>
                                            {% else %}
                                            <span class="badge badge-light px-2 py-1">{{ question.voter.count }}</span>
                                            {% endif %}
                                        </td>
                                        <td class="text-start">
                                            <a class="text-black text-decoration-none" href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                                            {% if question.answer_set.count  > 0 %}
                                                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                                            {% endif %}
                                        </td>
                                        <td>{{ question.author.username }}</td>
                                        <td>{{ question.hits }}</td>
                                        <td>{{ question.modify_date }}</td>
                                    </tr>
                                {%  endfor %}
                                {%  else %}
                                    <tr>
                                        <td colspan="4" style="text-align: center;">질문이 없습니다.</td>
                                    </tr>
                                {%  endif %}
                                </tbody>
                            </table>
                            <!-- 페이징 처리 시작 -->
                            <ul class="pagination justify-content-center">
                                {% if question_list.has_previous %}
                                    <li class="page-item">
                                        <a class="page-link" data-page="{{ question_list.previous_page_number }}" href="javascript:void(0)">이전</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" tabindex="-1" aria-disabled="true" href="#">이전</a>
                                    </li>
                                {% endif %}
                                {% for page_number in question_list.paginator.page_range %}
                                    {% if page_number >= question_list.number|add:-5 and page_number <= question_list.number|add:5 %}
                                    {% if page_number == question_list.number %}
                                        <li class="page-item active" aria-current="page">
                                            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
                                        </li>
                                    {% else %}
                                        <li class="page-item">
                                            <a class="page-link" data-page="{{ page_number }}" href="javascript:void(0)">{{ page_number }}</a>
                                        </li>
                                    {% endif %}
                                    {% endif %}
                                {% endfor %}
                                {% if question_list.has_next %}
                                    <li class="page-item">
                                        <a class="page-link" data-page="{{ question_list.next_page_number }}" href="javascript:void(0)">{{ page_number }}다음</a>
                                    </li>
                                {% else %}
                                    <li class="page-item disabled">
                                        <a class="page-link" tabindex="-1" aria-disabled="true" href="javascript:void(0)">다음</a>
                                    </li>
                                {% endif %}
                            </ul>
                            <!-- 페이징 처리 끝 -->
                            <a href="{% url 'pybo:question_create' %}" class="btn btn-primary">질문 등록하기</a>

                            <form id="searchForm" method="get" action="{% url 'pybo:question_list' category.id %}">
                                <input type="hidden" id="kw" name="kw" value="{{ kw|default_if_none:'' }}">
                                <input type="hidden" id="page" name="page" value="{{ page }}">
                                <input type="hidden" id="sort" name="sort" value="{{ sort }}">
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript">
        const sort_radio = document.getElementsByName('btnradio');
        const sel_var = document.getElementById('sort').value;
        for(var i=0; i<sort_radio.length; i++) {
            if(sort_radio[i].value == sel_var) {
                sort_radio[i].checked = true;
            }
        }


        Array.from(sort_radio).forEach(function(element) {
            element.addEventListener('change', function() {
                if(element.checked) {
                    document.getElementById('page').value = 1;
                    document.getElementById('sort').value = element.value;
                    document.getElementById('searchForm').submit();
                }
            });
        });

        const page_elements = document.getElementsByClassName("page-link");
        Array.from(page_elements).forEach(function(element) {
            element.addEventListener('click', function() {
                document.getElementById('page').value = this.dataset.page;
                document.getElementById('sort').value = document.getElementById('sort').value;
                document.getElementById('searchForm').submit();
            });
        });
        const btn_search = document.getElementById("btn_search");
        btn_search.addEventListener('click', function() {
            document.getElementById('kw').value = document.getElementById('search_kw').value;
            document.getElementById('page').value = 1;
            document.getElementById('sort').value = "recent";
            document.getElementById('searchForm').submit();
        });
    </script>
{% endblock %}