mysite/common/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'common'

urlpatterns = [
    path('login/', auth_views.LoginView.as_view(template_name='common/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(), name='logout'),
    path('signup/', views.signup, name='signup'),
    path('profile/<int:user_id>', views.profile, name='profile'),

    path('password/find', views.password_find, name='password_find'),
    path('password/modify/<int:user_id>', views.password_modify, name='password_modify'),

    path('id/find/', views.id_find, name='id_find'),
]

mysite/config/urls.py
from django.contrib import admin
from django.urls import path, include
from pybo.views import base_views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('pybo/', include('pybo.urls')),
    path('common/', include('common.urls')),
    path('', base_views.index, name='index'),
]

mysite/pybo/urls.py
from django.urls import path
from .views import base_views, question_views, answer_views, comment_views

app_name = 'pybo'

urlpatterns = [
    # base_views.py
    path('', base_views.index, name='index'),
    path('question/detail/<int:question_id>/', base_views.detail, name='detail'),

    # question_views.py
    path('question/create/', question_views.question_create, name='question_create'),
    path('question/modify/<int:question_id>/', question_views.question_modify, name='question_modify'),
    path('question/delete/<int:question_id>/', question_views.question_delete, name='question_delete'),
    path('question/vote/<int:question_id>/', question_views.question_vote, name='question_vote'),
    path('question/vote/del/<int:question_id>/', question_views.question_vote_del, name='question_vote_del'),
    path('question/list/<int:category_id>/', question_views.question_list, name='question_list'),

    # answer_views.py
    path('answer/create/<int:question_id>/', answer_views.answer_create, name='answer_create'),
    path('answer/modify/<int:answer_id>/', answer_views.answer_modify, name='answer_modify'),
    path('answer/delete/<int:answer_id>/', answer_views.answer_delete, name='answer_delete'),
    path('answer/vote/<int:answer_id>/', answer_views.answer_vote, name='answer_vote'),
    path('answer/vote/del/<int:answer_id>/', answer_views.answer_vote_del, name='answer_vote_del'),

    # comment_views.py
    path('question/comment/create/<int:question_id>/', comment_views.question_comment_create, name='question_comment_create'),
    path('answer/comment/create/<int:answer_id>/<str:page_num>', comment_views.answer_comment_create, name='answer_comment_create'),
    path('comment/vote/<int:question_id>?<int:comment_id>', comment_views.comment_vote, name='comment_vote'),
    path('comment/vote/del/<int:question_id>?<int:comment_id>', comment_views.comment_vote_del, name='comment_vote_del'),
    path('comment/del/<int:question_id>?<int:comment_id>', comment_views.comment_delete, name='comment_delete'),
    path('comment/modify/<int:question_id>?<int:comment_id>', comment_views.comment_modify, name='comment_modify'),
]

mysite/common/models.py
from django.db import models

# Create your models here.

mysite/pybo/models.py
# Create your models here.
from django.db import models
from django.contrib.auth.models import User


class Category(models.Model):
    subject = models.CharField(max_length=200)


class Comment(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_comment')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_comment')
    parent_content = models.TextField(null=True, default='')
    content = models.TextField(null=True, default='')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_comment')


class Question(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_question')
    category = models.ForeignKey(Category, on_delete=models.CASCADE, related_name='category_question')
    subject = models.CharField(max_length=200)          # 글자 수의 길이가 제한된 텍스트를 이용할 때
    content = models.TextField(null=True, default='')   # 글자 수를 제한할 수 없는 텍스트를 이용할 때
    create_date = models.DateTimeField()                # 생성된 날짜와 시간에 관계된 필드.
    modify_date = models.DateTimeField(null=True, blank=True)               # 수정 날짜
    voter = models.ManyToManyField(User, related_name='voter_question')     # 추천인 추가
    comments = models.ManyToManyField(Comment, related_name='comment_question')
    hits = models.DecimalField(max_digits=7, decimal_places=0, default=0)

    def __str__(self):
        return self.subject


class Answer(models.Model):
    author = models.ForeignKey(User, on_delete=models.CASCADE, related_name='author_answer')
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    content = models.TextField(null=True, default='')
    create_date = models.DateTimeField()
    modify_date = models.DateTimeField(null=True, blank=True)
    voter = models.ManyToManyField(User, related_name='voter_answer')
    comments = models.ManyToManyField(Comment, related_name='comment_answer')

mysite/common/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class UserForm(UserCreationForm):
    email = forms.EmailField(label="이메일")

    class Meta:
        model = User
        fields = ["username", "password1", "password2", "email"]


class PasswordFindForm(forms.Form):
    username = forms.CharField(max_length=20, label="사용자이름")
    email = forms.EmailField(label="이메일")


class PasswordForm(UserCreationForm):
    class Meta:
        model = User
        fields = ["password1", "password2"]


class IDFindForm(forms.Form):
    email = forms.EmailField(label="이메일")

mysite/common/views.py
# Create your views here.
from django.contrib import messages
from django.contrib.auth import authenticate, login
from django.contrib.auth.models import User
from django.contrib.auth.decorators import login_required
from django.shortcuts import render, redirect, get_object_or_404
from common.forms import UserForm, PasswordFindForm, PasswordForm, IDFindForm

from pybo.models import Question, Answer, Comment


def signup(request):
    if request.method == "POST":
        form = UserForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get('username')
            raw_password = form.cleaned_data.get('password1')
            user = authenticate(username=username, password=raw_password)   # 사용자 인증
            login(request, user)    # 로그인
            return redirect('pybo:index')
    else:
        form = UserForm()
    return render(request, 'common/signup.html', {'form': form})


@login_required(login_url='common:login')
def profile(request, user_id):
    if request.method == "POST":
        user = get_object_or_404(User, pk=user_id)
        raw_password = request.POST.get('password')
        if user.check_password(raw_password):
            return redirect('common:password_modify', user_id=user_id)
        else:
            messages.error(request, '비밀번호가 틀렸습니다.')

    question_list = Question.objects.filter(author_id=user_id).order_by('create_date')
    answer_list = Answer.objects.filter(author_id=user_id).order_by('create_date')
    comment_list = Comment.objects.filter(author_id=user_id).order_by('create_date')
    context = {'question_list': question_list, 'answer_list': answer_list, 'comment_list': comment_list}
    return render(request, 'common/profile.html', context)


def password_find(request):
    if request.method == "POST":
        form = PasswordFindForm(request.POST)
        if form.is_valid():
            username = form.cleaned_data['username']
            email = form.cleaned_data['email']
            if not User.objects.filter(username=username).exists():
                messages.error(request, '존재하지 않는 ID입니다.')
            elif not User.objects.filter(email=email).exists():
                messages.error(request, '존재하지 않는 email입니다.')
            else:
                user = User.objects.get(username=username)
                return redirect('common:password_modify', user_id=user.id)

    else:
        form = PasswordFindForm()
    return render(request, 'common/password_find.html', {'form': form})


def password_modify(request, user_id):
    user = User.objects.get(id=user_id)
    pre_password = user.password
    if request.method == "POST":
        form = PasswordForm(request.POST)
        if form.is_valid():
            new_password = form.cleaned_data.get('password1')
            if pre_password == new_password:
                messages.error(request, '이전 비밀번호와 동일합니다.')
            else:
                user.set_password(new_password)
                user.save()
                user = authenticate(username=user.username, password=new_password)
                return redirect('common:login')
    else:
        form = PasswordForm()
    context = {'form': form}
    return render(request, 'common/password_modify.html', context)


def id_find(request):
    if request.method == "POST":
        form = IDFindForm(request.POST)
        if form.is_valid():
            email = form.cleaned_data['email']
            if not User.objects.filter(email=email).exists():
                messages.error(request, '존재하지 않는 email입니다.')
            else:
                user = User.objects.get(email=email)
                context = {'username': user.username}
                return render(request, 'common/id_find_result.html', context)
    else:
        form = IDFindForm()
    context = {'form': form}
    return render(request, 'common/id_find.html', {'form': form})

mysite/templates/common/id_find.html
{% extends "base.html" %}
{% block content %}
    <div id="content_box" class="container my-3 py-3">
        <div class="row">
            <div class="d-flex flex-column m-3 py-2 mx-auto" style="height: auto !important;">
                <h3 class="font-weight-bold" style="text-align:center;">사용자ID 찾기</h3>
                <form method="post" action="{% url 'common:id_find' %}" class="row g-4 border-top border-secondary my-3 mx-auto">
                    {% csrf_token %}
                    <div class="mb-3">
                        {% include "messages_errors.html" %}
                        {% include 'form_errors.html' %}
                    </div>
                    <div class="mb-3">
                        <label for="email">이메일</label>
                        <input type="text" class="form-control" name="email" id="email"
                               value="{{ form.email.value|default_if_none:'' }}">
                    </div>
                    <div class="d-grid gap-2 mb-3 mx-auto">
                        <button type="submit" class="btn btn-primary">사용자ID 찾기</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

mysite/templates/common/id_find_result.html
{% extends "base.html" %}
{% block content %}
    <div id="content_box" class="container my-3 py-3">
        <div class="row">
            <div class="d-flex flex-column m-3 py-2 mx-auto" style="height: auto !important;">
                <h3 class="font-weight-bold" style="text-align:center;">사용자ID 찾기</h3>
                <div class="row g-4 border-top border-secondary my-3 mx-auto">
                    <div class="mb-3" style="text-align:center; font-size:20px;">
                        사용자 ID는 <strong>{{ username }}</strong>입니다.
                    </div>
                    <div class="container px-4 mb-3">
                        <div class="row gx-5">
                            <div class="col d-grid gap-2">
                                <a href="{% url 'common:login' %}" class="btn btn-primary">로그인 하기</a>
                            </div>
                            <div class="col d-grid gap-2">
                                <a href="{% url 'common:password_find' %}" class="btn btn-primary">비밀번호 찾기</a>
                            </div>
                        </div>
                    </div>
                </div>

            </div>
        </div>
    </div>
{% endblock %}

mysite/templates/common/login.html
{% extends "base.html" %}
{% block content %}
    <div id="content_box" class="container my-3 py-3">
        <div class="row">
            <div class="m-3 py-2 mx-auto" style="height: auto !important;">
                <div class="d-flex flex-column">
                    <div class="border border-secondary border-1 mx-auto">
                        <h3 class="font-weight-bold" style="text-align:center;">Login</h3>
                        <form method="post" action="{% url 'common:login' %}" class="row g-4 mx-auto">
                            {% csrf_token %}
                            <div class="mb-3">
                                {% include "form_errors.html" %}
                            </div>
                            <div class="mb-3">
                                <label for="username">사용자ID</label>
                                <input type="text" class="form-control" name="username" id="username"
                                       value="{{ form.username.value|default_if_none:'' }}">
                            </div>
                            <div class="mb-3">
                                <label for="password">비밀번호</label>
                                <input type="password" class="form-control mx-auto" name="password" id="password">
                                <div class="form-check">
                                    <input class="form-check-input" type="checkbox" id="showPassword">
                                    <label class="form-check-label" for="showPassword">비밀번호 표시</label>
                                </div>
                            </div>
                            <div class="d-grid gap-2 mb-3 mx-auto">
                                <button type="submit" class="btn btn-primary">로그인</button>
                            </div>
                        </form>
                    </div>
                    <div class="my-action-buttons row-cols-3 mx-auto p-3">
                        <a href="{% url 'common:id_find' %}" class="my-action">
                            아이디 찾기
                        </a>
                        |
                        <a href="{% url 'common:password_find' %}"  class="my-action">
                            비밀번호 찾기 및 변경
                        </a>
                        |
                        <a href="{% url 'common:signup' %}" class="my-action">
                            회원가입
                        </a>
                    </div>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript">
        const show_password = document.getElementById("showPassword");
        show_password.addEventListener('click', function() {
            if(show_password.checked) {
                document.getElementById("password").setAttribute("type", "text");
            }
            else {
                document.getElementById("password").setAttribute("type", "password");
            }
        });
    </script>
{% endblock %}

mysite/templates/common/password_find.html
{% extends "base.html" %}
{% block content %}
    <div id="content_box" class="container my-3 py-3">
        <div class="row">
            <div class="d-flex flex-column m-3 py-2 mx-auto" style="height: auto !important;">
                <h3 class="font-weight-bold" style="text-align:center;">비밀번호 찾기</h3>
                <form method="post" action="{% url 'common:password_find' %}" class="row g-4 border-top border-secondary my-3 mx-auto">
                    {% csrf_token %}
                    <div class="mb-3">
                        {% include "messages_errors.html" %}
                        {% include 'form_errors.html' %}
                    </div>
                    <div class="mb-3">
                        <label for="email">이메일</label>
                        <input type="text" class="form-control" name="email" id="email"
                               value="{{ form.email.value|default_if_none:'' }}">
                    </div>
                    <div class="mb-3">
                        <label for="username">사용자ID</label>
                        <input type="text" class="form-control" name="username" id="username"
                               value="{{ form.username.value|default_if_none:'' }}">
                    </div>
                    <div class="d-grid gap-2 mb-3 mx-auto">
                        <button type="submit" class="btn btn-primary">비밀번호 찾기</button>
                    </div>
                </form>
            </div>
        </div>
    </div>
{% endblock %}

mysite/templates/common/profile.html
{% extends 'base.html' %}
{% load pybo_filter %}
{% block content %}
    <div id="content_box" class="container my-3 py-3">
        <div class="row">
            <div class="m-3 py-2 mx-auto" style="height: auto !important;">
                <h3 class="pb-3 mb-0 border-bottom border-secondary font-weight-bold">Profile</h3>
                <div class="card my-3 border rounded">
                    <div class="card-header">
                        사용자 정보
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item p-0">
                            <div class="row align-items-start m-0 py-0">
                                <div class="col-1 border-end border-1 my-0 p-2" style="text-align:center;">
                                    Email
                                    <div style="height:6px;"></div>
                                </div>
                                <div class="col-6 my-0 py-2">
                                    <input type="text" size="45" value="{{ user.email }}" disabled>
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item p-0">
                            <div class="row align-items-start m-0 py-0">
                                <div class="col-1 border-end border-1 m-0 p-2" style="text-align:center;">
                                    ID
                                    <div style="height:6px;"></div>
                                </div>
                                <div class="col-6 m-0 py-2">
                                    <input type="text" size="45" value="{{ user.username }}" disabled>
                                </div>
                            </div>
                        </li>
                        <li class="list-group-item p-0">
                            <form id="passwordForm" method="post" action="{% url 'common:profile' user.id %}" class="row align-items-start m-0 py-0">
                                {% csrf_token %}
                                <div class="col-1 border-end border-1 m-0 p-2 py-2" style="text-align:center;">
                                    비밀번호
                                    <div style="height:38px;"></div>
                                </div>
                                <div class="col-4 m-0 my-1">
                                    <div class="m-0 py-1">
                                        <input name="password" id="password" type="password" size="45">
                                    </div>
                                    <div class="form-check m-0 my-1">
                                        <input class="form-check-input" type="checkbox" id="showPassword">
                                        <label class="form-check-label" for="showPassword">비밀번호 표시</label>
                                    </div>
                                </div>
                                <div class="col-auto m-0 p-0 my-1 py-1">
                                    <input type="submit" class="btn btn-outline-primary btn-sm" value="비밀번호 변경">
                                </div>
                                {% if messages %}
                                    <div class="col-auto alert alert-danger m-1 my-2 py-1">
                                    {% for message in messages %}
                                        {{ message.message }}
                                    {% endfor %}
                                    </div>
                                {% endif %}
                            </form>
                        </li>
                    </ul>
                </div>
                <div class="card my-3 border rounded">
                    <div class="card-header">
                        작성 글 목록
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <table class="table">
                                <thead>
                                    <tr class="text-center table-light">
                                        <th>추천</th>
                                        <th>게시판</th>
                                        <th style="width: 50%">제목</th>
                                        <th>날짜</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if question_list %}
                                {% for question in question_list %}
                                    <tr class="text-center">
                                        <td class="align-middle">
                                            {% if question.voter.count > 0 %}
                                            <span class="badge badge-warning px-2 py-1">{{ question.voter.count }}</span>
                                            {% else %}
                                            <span class="badge badge-light px-2 py-1">{{ question.voter.count }}</span>
                                            {% endif %}
                                        </td>
                                        <td class="align-middle">{{ question.category.subject }}</td>
                                        <td class="text-start">
                                            <a class="text-black text-decoration-none" href="{% url 'pybo:detail' question.id %}">{{ question.subject }}</a>
                                            {% if question.answer_set.count  > 0 %}
                                                <span class="text-danger small mx-2">{{ question.answer_set.count }}</span>
                                            {% endif %}
                                            {% if question.comments.count > 0 %}
                                                <i class="fa-solid fa-comment"></i> {{ question.comments.count }}
                                            {% endif %}
                                        </td>
                                        <td class="align-middle">{{ question.modify_date }}</td>
                                    </tr>
                                {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="3" style="text-align: center;">작성한 질문이 없습니다.</td>
                                    </tr>
                                {% endif %}
                                </tbody>
                            </table>
                        </li>
                    </ul>
                </div>
                <div class="card my-3 border rounded">
                    <div class="card-header">
                        작성 답변 목록
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <table class="table">
                                <thead>
                                    <tr class="text-center table-light">
                                        <th>추천</th>
                                        <th>카테고리</th>
                                        <th>질문 제목</th>
                                        <th style="width: 40%">내용</th>
                                        <th>날짜</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if answer_list %}
                                {% for answer in answer_list %}
                                    <tr class="text-center">
                                        <td class="align-middle">
                                            {% if answer.voter.count > 0 %}
                                            <span class="badge badge-warning px-2 py-1">{{ answer.voter.count }}</span>
                                            {% else %}
                                            <span class="badge badge-light px-2 py-1">{{ answer.voter.count }}</span>
                                            {% endif %}
                                        </td>
                                        <td class="align-middle">{{ answer.question.category.subject }}</td>
                                        <td class="align-middle">
                                            <a class="text-black text-decoration-none" href="{% url 'pybo:detail' answer.question.id %}">{{ answer.question.subject }}</a>
                                        </td>
                                        <td class="text-start">
                                            {{ answer.content|mark }}
                                            {% if answer.comments.count > 0 %}
                                                <i class="fa-solid fa-comment"></i> {{ answer.comments.count }}
                                            {% endif %}
                                        </td>
                                        <td class="align-middle">{{ answer.modify_date }}</td>
                                    </tr>
                                {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="5" style="text-align:center;">작성한 답변이 없습니다.</td>
                                    </tr>
                                {% endif %}
                                </tbody>
                            </table>
                        </li>
                    </ul>
                </div>
                <div class="card my-3 border rounded">
                    <div class="card-header">
                        작성 댓글 목록
                    </div>
                    <ul class="list-group list-group-flush">
                        <li class="list-group-item">
                            <table class="table">
                                <thead>
                                    <tr class="text-center table-light">
                                        <th>추천</th>
                                        <th>카테고리</th>
                                        <th style="width: 30%">질문 혹은 답변 요약</th>
                                        <th style="width: 30%">내용</th>
                                        <th>작성일시</th>
                                    </tr>
                                </thead>
                                <tbody>
                                {% if comment_list %}
                                {% for comment in comment_list %}
                                    <tr class="text-center">
                                        <td class="align-middle">
                                            {% if comment.voter.count > 0 %}
                                            <span class="badge badge-warning px-2 py-1">{{ comment.voter.count }}</span>
                                            {% else %}
                                            <span class="badge badge-light px-2 py-1">{{ comment.voter.count }}</span>
                                            {% endif %}
                                        </td>
                                        <td class="align-middle">
                                            {{ comment.category.subject }}
                                        </td>
                                        <td class="text-start align-middle">
                                            {{ comment.parent_content|mark }}
                                        </td>
                                        <td class="text-start">
                                            {{ comment.content }}
                                        </td>
                                        <td class="align-middle">
                                            {% if comment.modify_date %}
                                                수정: {{ comment.modify_date }}
                                            {% else %}
                                                {{ comment.create_date }}
                                            {% endif %}
                                        </td>
                                    </tr>
                                {% endfor %}
                                {% else %}
                                    <tr>
                                        <td colspan="5" style="text-align:center;">작성한 댓글이 없습니다.</td>
                                    </tr>
                                {% endif %}
                                </tbody>
                            </table>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
{% endblock %}
{% block script %}
    <script type="text/javascript">
        const show_password = document.getElementById("showPassword");
        show_password.addEventListener('click', function() {
            if(show_password.checked) {
                document.getElementById("password").setAttribute("type", "text");
            }
            else {
                document.getElementById("password").setAttribute("type", "password");
            }
        });
    </script>
{% endblock %}